//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSSend
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.adpdigital.com/services/messaging", ConfigurationName="SMSSend.JaxRpcMessagingService")]
    public interface JaxRpcMessagingService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        System.Threading.Tasks.Task<SMSSend.sendMultipleResponse> sendMultipleAsync(SMSSend.sendMultipleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getBalanceReturn")]
        System.Threading.Tasks.Task<SMSSend.BalanceResult> getBalanceAsync(string userName, string password, short facilityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="changePasswordReturn")]
        System.Threading.Tasks.Task<short> changePasswordAsync(string userName, string currentPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getStatusReturn")]
        System.Threading.Tasks.Task<short> getStatusAsync(long messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="receiveReturn")]
        System.Threading.Tasks.Task<SMSSend.ReceiveResult> receiveAsync(string userName, string password, string shortNumber, long start, int maxSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        System.Threading.Tasks.Task<SMSSend.sendResponse> sendAsync(SMSSend.sendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="reportReturn")]
        System.Threading.Tasks.Task<SMSSend.ReportResult> reportAsync(string userName, string password, string shortNumber, string fromClientId, string clientId, string fromId, string id, int maxSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        System.Threading.Tasks.Task<SMSSend.statusReportResponse> statusReportAsync(SMSSend.statusReportRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class MultiAddressMessageObject
    {
        
        private string contentField;
        
        private short encodingField;
        
        private string[] phoneNumbersField;
        
        private string[] clientIdsField;
        
        private System.DateTime dueTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short encoding
        {
            get
            {
                return this.encodingField;
            }
            set
            {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] phoneNumbers
        {
            get
            {
                return this.phoneNumbersField;
            }
            set
            {
                this.phoneNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] clientIds
        {
            get
            {
                return this.clientIdsField;
            }
            set
            {
                this.clientIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime dueTime
        {
            get
            {
                return this.dueTimeField;
            }
            set
            {
                this.dueTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class OutgoingMessage
    {
        
        private long idField;
        
        private string clientIdField;
        
        private short statusField;
        
        private string toField;
        
        private System.DateTime timeField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string clientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public short status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class StatusReport
    {
        
        private long idField;
        
        private short statusField;
        
        private string clientIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string clientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                this.clientIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class MessageObject
    {
        
        private int chunkField;
        
        private string clientIdField;
        
        private string contentField;
        
        private short encodingField;
        
        private long idField;
        
        private string phoneNumberField;
        
        private short statusField;
        
        private System.Nullable<System.DateTime> timeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int chunk
        {
            get
            {
                return this.chunkField;
            }
            set
            {
                this.chunkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string clientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public short encoding
        {
            get
            {
                return this.encodingField;
            }
            set
            {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string phoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public short status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class IncomingMessage
    {
        
        private string contentField;
        
        private short encodingField;
        
        private string fromField;
        
        private long idField;
        
        private object requestField;
        
        private short statusField;
        
        private System.Nullable<System.DateTime> timeField;
        
        private string toField;
        
        private short typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short encoding
        {
            get
            {
                return this.encodingField;
            }
            set
            {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public object request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public short status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public short type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReportResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusReportResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceiveResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BalanceResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public abstract partial class Result
    {
        
        private short statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class ReportResult : Result
    {
        
        private OutgoingMessage[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("messages", IsNullable=false)]
        public OutgoingMessage[] messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class StatusReportResult : Result
    {
        
        private StatusReport[] reportField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("report", IsNullable=false)]
        public StatusReport[] report
        {
            get
            {
                return this.reportField;
            }
            set
            {
                this.reportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class ReceiveResult : Result
    {
        
        private IncomingMessage[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("messages", IsNullable=false)]
        public IncomingMessage[] messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class BalanceResult : Result
    {
        
        private long balanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long balance
        {
            get
            {
                return this.balanceField;
            }
            set
            {
                this.balanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class SendResult : Result
    {
        
        private long[] idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", IsNullable=false)]
        public long[] id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMultiple", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class sendMultipleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=2)]
        public string shortNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=3)]
        public string sourcePort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=4)]
        public string destPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=5)]
        public short messageType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=6)]
        public bool longSupported;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute("messages")]
        public SMSSend.MultiAddressMessageObject[] messages;
        
        public sendMultipleRequest()
        {
        }
        
        public sendMultipleRequest(string userName, string password, string shortNumber, string sourcePort, string destPort, short messageType, bool longSupported, SMSSend.MultiAddressMessageObject[] messages)
        {
            this.userName = userName;
            this.password = password;
            this.shortNumber = shortNumber;
            this.sourcePort = sourcePort;
            this.destPort = destPort;
            this.messageType = messageType;
            this.longSupported = longSupported;
            this.messages = messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMultipleResponse", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class sendMultipleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public SMSSend.SendResult sendMultipleReturn;
        
        public sendMultipleResponse()
        {
        }
        
        public sendMultipleResponse(SMSSend.SendResult sendMultipleReturn)
        {
            this.sendMultipleReturn = sendMultipleReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class sendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=2)]
        public string sourceNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("destNo")]
        public string[] destNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=4)]
        public string sourcePort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=5)]
        public string destPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("clientId")]
        public string[] clientId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=7)]
        public short messageType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=8)]
        public short encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=9)]
        public bool longSupported;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=10)]
        public System.DateTime dueTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=11)]
        public string content;
        
        public sendRequest()
        {
        }
        
        public sendRequest(string userName, string password, string sourceNo, string[] destNo, string sourcePort, string destPort, string[] clientId, short messageType, short encoding, bool longSupported, System.DateTime dueTime, string content)
        {
            this.userName = userName;
            this.password = password;
            this.sourceNo = sourceNo;
            this.destNo = destNo;
            this.sourcePort = sourcePort;
            this.destPort = destPort;
            this.clientId = clientId;
            this.messageType = messageType;
            this.encoding = encoding;
            this.longSupported = longSupported;
            this.dueTime = dueTime;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendResponse", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class sendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public SMSSend.SendResult sendReturn;
        
        public sendResponse()
        {
        }
        
        public sendResponse(SMSSend.SendResult sendReturn)
        {
            this.sendReturn = sendReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="statusReport", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class statusReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=2)]
        public string shortNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=3)]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("ids")]
        public long[] ids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("clientIds")]
        public string[] clientIds;
        
        public statusReportRequest()
        {
        }
        
        public statusReportRequest(string userName, string password, string shortNumber, string type, long[] ids, string[] clientIds)
        {
            this.userName = userName;
            this.password = password;
            this.shortNumber = shortNumber;
            this.type = type;
            this.ids = ids;
            this.clientIds = clientIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="statusReportResponse", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class statusReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public SMSSend.StatusReportResult statusReportReturn;
        
        public statusReportResponse()
        {
        }
        
        public statusReportResponse(SMSSend.StatusReportResult statusReportReturn)
        {
            this.statusReportReturn = statusReportReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface JaxRpcMessagingServiceChannel : SMSSend.JaxRpcMessagingService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class JaxRpcMessagingServiceClient : System.ServiceModel.ClientBase<SMSSend.JaxRpcMessagingService>, SMSSend.JaxRpcMessagingService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public JaxRpcMessagingServiceClient() : 
                base(JaxRpcMessagingServiceClient.GetDefaultBinding(), JaxRpcMessagingServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MessagingService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JaxRpcMessagingServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(JaxRpcMessagingServiceClient.GetBindingForEndpoint(endpointConfiguration), JaxRpcMessagingServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JaxRpcMessagingServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(JaxRpcMessagingServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JaxRpcMessagingServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(JaxRpcMessagingServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JaxRpcMessagingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSSend.sendMultipleResponse> SMSSend.JaxRpcMessagingService.sendMultipleAsync(SMSSend.sendMultipleRequest request)
        {
            return base.Channel.sendMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSSend.sendMultipleResponse> sendMultipleAsync(string userName, string password, string shortNumber, string sourcePort, string destPort, short messageType, bool longSupported, SMSSend.MultiAddressMessageObject[] messages)
        {
            SMSSend.sendMultipleRequest inValue = new SMSSend.sendMultipleRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.shortNumber = shortNumber;
            inValue.sourcePort = sourcePort;
            inValue.destPort = destPort;
            inValue.messageType = messageType;
            inValue.longSupported = longSupported;
            inValue.messages = messages;
            return ((SMSSend.JaxRpcMessagingService)(this)).sendMultipleAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<SMSSend.BalanceResult> getBalanceAsync(string userName, string password, short facilityId)
        {
            return base.Channel.getBalanceAsync(userName, password, facilityId);
        }
        
        public System.Threading.Tasks.Task<short> changePasswordAsync(string userName, string currentPassword, string newPassword)
        {
            return base.Channel.changePasswordAsync(userName, currentPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<short> getStatusAsync(long messageId)
        {
            return base.Channel.getStatusAsync(messageId);
        }
        
        public System.Threading.Tasks.Task<SMSSend.ReceiveResult> receiveAsync(string userName, string password, string shortNumber, long start, int maxSize)
        {
            return base.Channel.receiveAsync(userName, password, shortNumber, start, maxSize);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSSend.sendResponse> SMSSend.JaxRpcMessagingService.sendAsync(SMSSend.sendRequest request)
        {
            return base.Channel.sendAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSSend.sendResponse> sendAsync(string userName, string password, string sourceNo, string[] destNo, string sourcePort, string destPort, string[] clientId, short messageType, short encoding, bool longSupported, System.DateTime dueTime, string content)
        {
            SMSSend.sendRequest inValue = new SMSSend.sendRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.sourceNo = sourceNo;
            inValue.destNo = destNo;
            inValue.sourcePort = sourcePort;
            inValue.destPort = destPort;
            inValue.clientId = clientId;
            inValue.messageType = messageType;
            inValue.encoding = encoding;
            inValue.longSupported = longSupported;
            inValue.dueTime = dueTime;
            inValue.content = content;
            return ((SMSSend.JaxRpcMessagingService)(this)).sendAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<SMSSend.ReportResult> reportAsync(string userName, string password, string shortNumber, string fromClientId, string clientId, string fromId, string id, int maxSize)
        {
            return base.Channel.reportAsync(userName, password, shortNumber, fromClientId, clientId, fromId, id, maxSize);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSSend.statusReportResponse> SMSSend.JaxRpcMessagingService.statusReportAsync(SMSSend.statusReportRequest request)
        {
            return base.Channel.statusReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSSend.statusReportResponse> statusReportAsync(string userName, string password, string shortNumber, string type, long[] ids, string[] clientIds)
        {
            SMSSend.statusReportRequest inValue = new SMSSend.statusReportRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.shortNumber = shortNumber;
            inValue.type = type;
            inValue.ids = ids;
            inValue.clientIds = clientIds;
            return ((SMSSend.JaxRpcMessagingService)(this)).statusReportAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MessagingService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MessagingService))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.adpdigital.com/services/MessagingService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return JaxRpcMessagingServiceClient.GetBindingForEndpoint(EndpointConfiguration.MessagingService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return JaxRpcMessagingServiceClient.GetEndpointAddress(EndpointConfiguration.MessagingService);
        }
        
        public enum EndpointConfiguration
        {
            
            MessagingService,
        }
    }
}
